# Generated by Django 4.0.1 on 2022-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_emailtaskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtaskreport',
            name='send_time',
            field=models.TimeField(null=True),
        ),
    ]
