# Generated by Django 4.0.1 on 2022-02-12 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_emailtaskreport_send_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtaskreport',
            name='sent',
        ),
        migrations.AlterField(
            model_name='emailtaskreport',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
