# Generated by Django 4.0.1 on 2022-02-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_emailtaskreport_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtaskreport',
            name='content',
        ),
        migrations.RemoveField(
            model_name='emailtaskreport',
            name='subject',
        ),
    ]
